// These constants are used to populate the browse landing page with random subjects and call numbers. The shuffleArray function is used to randomize the order of the subjects and call numbers each time the component is initialized.

export const browseSelections = {
  lcSubjects: [
    'Arab-Israeli conflict',
    'Automobile drivers Psychology',
    'Asian American gay people',
    'Deception Psychological aspects',
    'Food Philosophy',
    'Hormone therapy',
    'Freedom of speech United States History',
    'Polarization (Social sciences)',
    'Pan-Africanism History',
    'Racism in education',
    'Singers United States',
    'Strikes and lockouts',
    'Technology Social aspects',
    'Tulsa Race Massacre, Tulsa, Okla., 1921',
    'Women Suffrage United States History',
  ],
  homoitSubjects: [
    'African American LGBTQ+ people',
    'Bisexual fiction',
    'Coming out',
    'Gay biographies',
    'Gay couples',
    'Genderqueer people',
    'Lesbian liberation',
    'LGBTQ+ athletes',
    'LGBTQ+ parents',
    'Non-binary people',
    'Queer activism',
    'Trans women'
  ],
  lcGenres: [
    'Black humor',
    'Campus fiction',
    'Detective and mystery fiction',
    'Diaries',
    'Environmental films',
    'Love poetry',
    'Magic realist fiction',
    'Manga',
    'Monologues (Drama)',
    'Narrative poetry',
    'One-act plays',
    'Paranormal comics',
    'Personal correspondence',
    'Prose poems',
    'Romantic comedy films',
    'Science fiction comics',
    'Utopian fiction'
  ],
  lcNames: [
    'A24 (Firm)',
    'Chaucer, Geoffrey, -1400',
    'Chekhov, Anton Pavlovich, 1860-1904',
    'Coogler, Ryan, 1986-',
    'Didion, Joan',
    'Galeano, Eduardo, 1940-2015',
    'Mandela, Nelson, 1918-2013',
    'Plato',
    'Pussy Riot (Musical group)',
    'Said, Edward W.',
    'Shelley, Mary Wollstonecraft, 1797-1851',
    'Smith, Zadie',
    'Wilder, Billy, 1906-2002',
    'X, Malcolm, 1925-1965'
  ],
  callNos: [
    {class: 'B528', desc: 'Stoicism'},
    {class: 'F1226', desc: 'History of Mexico'},
    {class: 'HQ73', desc: 'LGBTQ People'},
    {class: 'GV450', desc: 'Nudism'},
    {class: 'JC423', desc: 'Republicanism'},
    {class: 'HV7936.P8', desc: 'Police psychology'},
    {class: 'HV9471', desc: 'Corrections'},
    {class: 'ND1484', desc: 'Color in painting'},
    {class: 'P95', desc: 'Oral communication'},
    {class: 'PG3325', desc: 'Fyodor Dostoevsky'},
    {class: 'PN56', desc: 'Literature - Special topics'},
    {class: 'PS3552.U827', desc: 'Octavia Butler'},
    {class: 'Q335', desc: 'Artificial intelligence'},
    {class: 'QA269', desc: 'Game theory'},
    {class: 'QR171.G29', desc: 'Gastrointestinal system'},
    {class: 'RC553.A88', desc: 'Autism'},
    {class: 'T14.5', desc: 'Technology - Social aspects'},
    {class: 'TL152.35', desc: 'Drivers - Psychology'},
    {class: 'ZA3073', desc: 'Information Ethics'},
  ],
} as const satisfies { lcSubjects: readonly string[]; homoitSubjects: readonly string[]; lcGenres: readonly string[]; lcNames: readonly string[]; callNos: readonly { class: string; desc: string }[] };
