// These constants are used to populate the browse landing page with random subjects and call numbers. The shuffleArray function is used to randomize the order of the subjects and call numbers each time the component is initialized.

export const browseSelections = {
  subjects: [
    'Arab-Israeli conflict',
    'Automobile drivers Psychology',
    'Asian American gay people',
    'Deception Psychological aspects',
    'Food Philosophy',
    'Hormone therapy',
    'Freedom of speech United States History',
    'Polarization (Social sciences)',
    'Pan-Africanism History',
    'Racism in education',
    'Singers United States',
    'Strikes and lockouts',
    'Technology Social aspects',
    'Tulsa Race Massacre, Tulsa, Okla., 1921',
    'Women Suffrage United States History',
  ],
  callNos: [
    {class: 'B528', desc: 'Stoicism'},
    {class: 'F1226', desc: 'History of Mexico'},
    {class: 'HQ73', desc: 'LGBTQ People'},
    {class: 'GV450', desc: 'Nudist sunbathing'},
    {class: 'JC423', desc: 'Republicanism'},
    {class: 'HV7936.P8', desc: 'Police psychology'},
    {class: 'HV9471', desc: 'Corrections'},
    {class: 'ND1484', desc: 'Color in painting'},
    {class: 'P95', desc: 'Oral communication'},
    {class: 'PG3325', desc: 'Fyodor Dostoevsky'},
    {class: 'PN56', desc: 'Literature - Special topics'},
    {class: 'PS3552.U827', desc: 'Octavia Butler'},
    {class: 'Q335', desc: 'Artificial intelligence'},
    {class: 'QA269', desc: 'Game theory'},
    {class: 'QR171.G29', desc: 'Gastrointestinal system'},
    {class: 'RC553.A88', desc: 'Autism'},
    {class: 'T14.5', desc: 'Technology - Social aspects'},
    {class: 'TL152.35', desc: 'Drivers - Psychology'},
    {class: 'ZA3073', desc: 'Information Ethics'},
  ],
} as const satisfies { subjects: readonly string[]; callNos: readonly { class: string; desc: string }[] };
